services:
  web:
    build: .
    image: iodocker-dgtic.sep.gob.mx/siisep/siisep-django:${APP_VERSION}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_VERSION=${APP_VERSION}
      - DJANGO_SETTINGS_MODULE=djangocrud.settings
    env_file:
      - .env
