version: '3.8'

services:
  web:
    build: .
    image: iodocker-dgtic.sep.gob.mx/siisep/siisep-django:1.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
