# Generated by Django 4.2.3 on 2023-10-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareasCondia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('uso_inmueble', models.CharField(blank=True, max_length=200, null=True)),
                ('riuf', models.CharField(blank=True, max_length=200, null=True)),
                ('superficie_rentable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('personal_ocupante', models.IntegerField(blank=True, null=True)),
                ('uso_suelo', models.CharField(blank=True, max_length=200, null=True)),
                ('no_contrato', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True)),
                ('monto_mensual_dictamen_estructural', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('correo1', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo2', models.EmailField(blank=True, max_length=254, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('propietario_representante', models.CharField(blank=True, max_length=200, null=True)),
                ('identificacion_oficial', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio_fiscal', models.TextField(blank=True, null=True)),
                ('justificacion_de_renta', models.TextField(blank=True, null=True)),
                ('renta_mensual_civa_segun_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_por_m2_civa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_asentamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('entre_vialidades_referencia1', models.CharField(blank=True, max_length=100, null=True)),
                ('entre_vialidades_referencia2', models.CharField(blank=True, max_length=100, null=True)),
                ('vialidad_posterior', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_ubicacion', models.TextField(blank=True, null=True)),
                ('fotoPresentacion', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('tipo_de_proceso', models.CharField(choices=[('Arrendamiento', 'Arrendamiento'), ('Legal', 'Legal'), ('Trámite de archivo', 'Trámite de archivo')], default='Arrendamiento', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_espacio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Solicitud de espacio o notificación a la UR')),
                ('tabla_superficie_maxima', models.FileField(blank=True, null=True, upload_to='', verbose_name='Tabla de superficie máxima a ocupar por institución (SMOI)')),
                ('justificacion_arrendamiento', models.FileField(blank=True, null=True, upload_to='', verbose_name='Justificación y autorización del arrendamiento ante el INDAABIN')),
                ('solicitud_disponibilidad', models.FileField(blank=True, null=True, upload_to='', verbose_name='Solicitud de disponibilidad de inmuebles de propiedad federal y respuesta del INDAABIN')),
                ('solicitud_arrendamiento_oficialia', models.FileField(blank=True, null=True, upload_to='', verbose_name='Solicitud y/o autorización del arrendamiento (Oficialía Mayor)')),
                ('notificacion_propietario_arrendar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Notificación al propietario para arrendar el inmueble')),
                ('solicitud_justipreciacion_renta', models.FileField(blank=True, null=True, upload_to='', verbose_name='Solicitud de justipreciación de renta')),
                ('notificacion_pago_derechos', models.FileField(blank=True, null=True, upload_to='', verbose_name='Notificación de pago de derechos del INDAABIN')),
                ('dictamen_justipreciacion_renta', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dictamen de justipreciación de renta')),
                ('oficio_revision_juridica_respuesta', models.FileField(blank=True, null=True, upload_to='', verbose_name='Oficio de revisión jurídica y respuesta')),
                ('justificacion_plurianual', models.FileField(blank=True, null=True, upload_to='', verbose_name='Justificación plurianual')),
                ('oficio_solicitud_registro_obligacional', models.FileField(blank=True, null=True, upload_to='', verbose_name='Oficio de solicitud y registro obligacional (UAJ)')),
                ('registro_contrato_pagina_indaabin', models.FileField(blank=True, null=True, upload_to='', verbose_name='Registro de contrato en página del INDAABIN')),
                ('contrato_arrendamiento_convenios', models.FileField(blank=True, null=True, upload_to='', verbose_name='Contrato de arrendamiento y convenios')),
                ('notificacion_ur_subdireccion_obras_planos', models.FileField(blank=True, null=True, upload_to='', verbose_name='Notificación a la UR y Subdirección de Obras para la elaboración de los planos de adecuación de oficinas')),
                ('anexo_contrato_acta_recepcion_inmueble', models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexo 1 al contrato de arrendamiento, acta-recepción del inmueble')),
                ('documentos_inventario_condiciones', models.FileField(blank=True, null=True, upload_to='', verbose_name='Inventario y las condiciones de instalaciones y equipos propios del inmueble, validado por la Subdirección de Obras')),
                ('documentos_dictamen_seguridad_estructural', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dictamen de seguridad estructural emitido por un Director Responsable del Inmueble')),
                ('documentos_usos_limitaciones', models.FileField(blank=True, null=True, upload_to='', verbose_name='Usos permitidos y en general todas las limitaciones derivadas de las características del inmueble')),
                ('documentos_acta_entrega_trabajos', models.FileField(blank=True, null=True, upload_to='', verbose_name='Acta-Entrega de los trabajos de adecuación de oficinas a cargo de la Subdirección de obras')),
                ('anexo_contrato_plano_distribucion_personal', models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexo 2 al contrato de arrendamiento plano de distribución de personal (adecuación de oficinas autorizado)')),
                ('notificacion_disponibilidad_ur', models.FileField(blank=True, null=True, upload_to='', verbose_name='Oficio de notificación de disponibilidad del inmueble a la UR')),
                ('actas_entrega_asignacion_espacio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Actas-entrega de asignación de espacio a las Unidades Administrativas')),
                ('documentos_legales_escritura_inmueble', models.FileField(blank=True, null=True, upload_to='', verbose_name='Escritura del inmueble a arrendar (título de propiedad)')),
                ('documentos_legales_acta_constitutiva', models.FileField(blank=True, null=True, upload_to='', verbose_name='Testimonio de la escritura pública que contenga el acta constitutiva de la empresa que tenga carácter de arrendador, tratándose de personas morales y Registro Público de la Propiedad y el Comercio')),
                ('documentos_legales_escritura_cambio_regimen', models.FileField(blank=True, null=True, upload_to='', verbose_name='Escritura de cambio de régimen (si es el caso)')),
                ('documentos_legales_poder_notarial', models.FileField(blank=True, null=True, upload_to='', verbose_name='Escritura pública que contenga el poder notarial de la persona que pretenda suscribir el contrato en representación del arrendado')),
                ('documentos_legales_cedula_fiscal', models.FileField(blank=True, null=True, upload_to='', verbose_name='Cedula de identificación fiscal del arrendador, Registro Federal de Contribuyentes (RFC)')),
                ('documentos_legales_identificacion_oficial', models.FileField(blank=True, null=True, upload_to='', verbose_name='Identificación oficial vigente con fotografía y firma del arrendador o representante legal, credencial de elector (INE)')),
                ('documentos_legales_comprobante_domicilio_fiscal', models.FileField(blank=True, null=True, upload_to='', verbose_name='Comprobante de domicilio fiscal del arrendador')),
                ('documentos_tecnicos_planos_arquitectonicos', models.FileField(blank=True, null=True, upload_to='', verbose_name='Planos Arquitectónicos')),
                ('documentos_tecnicos_constancia_seguridad_estructural', models.FileField(blank=True, null=True, upload_to='', verbose_name='Registro de la constancia de seguridad estructural expedida por el GCDMX')),
                ('documentos_tecnicos_visto_bueno_seguridad_operacion', models.FileField(blank=True, null=True, upload_to='', verbose_name='Visto bueno de seguridad y operción expedida por el GCDMX')),
                ('documentos_tecnicos_ultimo_pago_predial', models.FileField(blank=True, null=True, upload_to='', verbose_name='Última boleta por concepto de pago del impuesto predial')),
                ('documentos_tecnicos_ultimo_pago_agua', models.FileField(blank=True, null=True, upload_to='', verbose_name='Última boleta por concepto de suministro de agua potable')),
                ('documentos_tecnicos_ultimo_pago_energia', models.FileField(blank=True, null=True, upload_to='', verbose_name='Último recibo por concepto de pago de servicio de energía eléctrica')),
                ('fundamento_legal', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fundamento Legal')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condia.tareascondia')),
            ],
        ),
    ]
