# Generated by Django 4.2.3 on 2023-10-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condia', '0002_alter_documentos_actas_entrega_asignacion_espacio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareascondia',
            name='actas_entrega_asignacion_espacio',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Actas-entrega de asignación de espacio a las Unidades Administrativas'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='anexo_contrato_acta_recepcion_inmueble',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Anexo 1 al contrato de arrendamiento, acta-recepción del inmueble'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='anexo_contrato_plano_distribucion_personal',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Anexo 2 al contrato de arrendamiento plano de distribución de personal (adecuación de oficinas autorizado)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='contrato_arrendamiento_convenios',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Contrato de arrendamiento y convenios'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='dictamen_justipreciacion_renta',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Dictamen de justipreciación de renta'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_acta_entrega_trabajos',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Acta-Entrega de los trabajos de adecuación de oficinas a cargo de la Subdirección de obras'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_dictamen_seguridad_estructural',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Dictamen de seguridad estructural emitido por un Director Responsable del Inmueble'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_inventario_condiciones',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Inventario y las condiciones de instalaciones y equipos propios del inmueble, validado por la Subdirección de Obras'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_acta_constitutiva',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Testimonio de la escritura pública que contenga el acta constitutiva de la empresa que tenga carácter de arrendador, tratándose de personas morales y Registro Público de la Propiedad y el Comercio'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_cedula_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Cedula de identificación fiscal del arrendador, Registro Federal de Contribuyentes (RFC)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_comprobante_domicilio_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Comprobante de domicilio fiscal del arrendador'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_escritura_cambio_regimen',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Escritura de cambio de régimen (si es el caso)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_escritura_inmueble',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Escritura del inmueble a arrendar (título de propiedad)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_identificacion_oficial',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Identificación oficial vigente con fotografía y firma del arrendador o representante legal, credencial de elector (INE)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_legales_poder_notarial',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Escritura pública que contenga el poder notarial de la persona que pretenda suscribir el contrato en representación del arrendado'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_tecnicos_constancia_seguridad_estructural',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Registro de la constancia de seguridad estructural expedida por el GCDMX'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_tecnicos_planos_arquitectonicos',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Planos Arquitectónicos'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_tecnicos_ultimo_pago_agua',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Última boleta por concepto de suministro de agua potable'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_tecnicos_ultimo_pago_energia',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Último recibo por concepto de pago de servicio de energía eléctrica'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_tecnicos_ultimo_pago_predial',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Última boleta por concepto de pago del impuesto predial'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_tecnicos_visto_bueno_seguridad_operacion',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta2Condia/', verbose_name='Visto bueno de seguridad y operción expedida por el GCDMX'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='documentos_usos_limitaciones',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Usos permitidos y en general todas las limitaciones derivadas de las características del inmueble'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='fundamento_legal',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta3Condia/', verbose_name='Fundamento Legal'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='justificacion_arrendamiento',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Justificación y autorización del arrendamiento ante el INDAABIN'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='justificacion_plurianual',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Justificación plurianual'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='notificacion_disponibilidad_ur',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Oficio de notificación de disponibilidad del inmueble a la UR'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='notificacion_pago_derechos',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Notificación de pago de derechos del INDAABIN'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='notificacion_propietario_arrendar',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Notificación al propietario para arrendar el inmueble'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='notificacion_ur_subdireccion_obras_planos',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Notificación a la UR y Subdirección de Obras para la elaboración de los planos de adecuación de oficinas'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='oficio_revision_juridica_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Oficio de revisión jurídica y respuesta'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='oficio_solicitud_registro_obligacional',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Oficio de solicitud y registro obligacional (UAJ)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='registro_contrato_pagina_indaabin',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Registro de contrato en página del INDAABIN'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='solicitud_arrendamiento_oficialia',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Solicitud y/o autorización del arrendamiento (Oficialía Mayor)'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='solicitud_disponibilidad',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Solicitud de disponibilidad de inmuebles de propiedad federal y respuesta del INDAABIN'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='solicitud_espacio',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Solicitud de espacio o notificación a la UR'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='solicitud_justipreciacion_renta',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Solicitud de justipreciación de renta'),
        ),
        migrations.AddField(
            model_name='tareascondia',
            name='tabla_superficie_maxima',
            field=models.FileField(blank=True, null=True, upload_to='Carpeta1Condia/', verbose_name='Tabla de superficie máxima a ocupar por institución (SMOI)'),
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
