# Generated by Django 5.1.1 on 2024-09-27 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosCreados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('dia', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('Nom_sala', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=10, null=True)),
                ('nivel', models.CharField(blank=True, max_length=10, null=True)),
                ('sala', models.CharField(blank=True, max_length=10, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, null=True)),
                ('coordina', models.CharField(blank=True, max_length=100, null=True)),
                ('preside', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('no_personas', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('servicios', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'permissions': [('add_evento', 'Can add evento in tasks app'), ('change_evento', 'Can change evento in tasks app'), ('delete_evento', 'Can delete evento in tasks app'), ('view_evento', 'Can view evento in tasks app')],
            },
        ),
        migrations.CreateModel(
            name='Task_eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
