# Generated by Django 5.0.4 on 2024-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDSJSEP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscreados',
            name='cargo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='eventoscreados',
            name='coordina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventoscreados',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='eventoscreados',
            name='preside',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventoscreados',
            name='servicios',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='eventoscreados',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
