# Generated by Django 5.0.4 on 2024-04-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDSJSEP', '0002_alter_eventoscreados_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscreados',
            name='contacto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='eventoscreados',
            name='no_personas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
