# Generated by Django 5.0.4 on 2024-05-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datosllamadasinmuebles',
            table='tasks_datosllamadasinmuebles',
        ),
    ]
