# Generated by Django 4.2.3 on 2024-08-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
