# Generated by Django 5.1.3 on 2025-08-20 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosavaluosimp',
            name='fecha_valor_de_avaluo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosavaluosimp',
            name='numero_de_avaluo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datosavaluosimp',
            name='uso_del_avaluo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='datosavaluosimp',
            name='valor_de_avaluo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='datosavaluosimp',
            name='valor_de_construccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='datosavaluosimp',
            name='valor_de_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='datostercerosimp',
            name='beneficiario',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('ASOCIACIÓN CIVIL', 'ASOCIACIÓN CIVIL'), ('ORGANISMO INTERNACIONAL', 'ORGANISMO INTERNACIONAL'), ('PERSONA FÍSICA', 'PERSONA FÍSICA'), ('PERSONA MORAL', 'PERSONA MORAL')], default='SIN INFORMACIÓN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datostercerosimp',
            name='nombre_beneficiario',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='datostercerosimp',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='datostercerosimp',
            name='tipo_usuario_tercero',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('ARRENDAMIENTO', 'ARRENDAMIENTO'), ('ASIGNACIÓN', 'ASIGNACIÓN'), ('AUTORIZACIÓN', 'AUTORIZACIÓN'), ('COMODATO', 'COMODATO'), ('CONCESIÓN', 'CONCESIÓN'), ('CONVENIO', 'CONVENIO'), ('USUFRUCTO', 'USUFRUCTO')], default='SIN INFORMACIÓN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento_ocupacionimp',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento_ocupacionimp',
            name='inscripcion_RPPF',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='documento_ocupacionimp',
            name='tipo_de_documento',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('ACTA DE ASAMBLEA EJIDATARIOS', 'ACTA DE ASAMBLEA EJIDATARIOS'), ('ACTA DE ENTREGA DE ESPACIOS EN INMUEBLES FEDERALES COMPARTIDOS', 'ACTA DE ENTREGA DE ESPACIOS EN INMUEBLES FEDERALES COMPARTIDOS'), ('ACTA DE ENTREGA DE OBRA', 'ACTA DE ENTREGA DE OBRA'), ('ACTA DE ENTREGA RECEPCIÓN', 'ACTA DE ENTREGA RECEPCIÓN'), ('ACTA DE OCUPACIÓN ADMINISTRATIVA', 'ACTA DE OCUPACIÓN ADMINISTRATIVA'), ('ACUERDO DE DESTINO', 'ACUERDO DE DESTINO'), ('ADQUISIONES POSTERIORES A 1004', 'ADQUISIONES POSTERIORES A 1004'), ('ARRENDAMIENTO', 'ARRENDAMIENTO'), ('ART. 59 FR. VI LGBN (ACTOS JURÍDICOS QUE INTERVIENE SFP)', 'ART. 59 FR. VI LGBN (ACTOS JURÍDICOS QUE INTERVIENE SFP)'), ('CERTIFICADO DE ASIGNACIÓN DE ESPACIOS EN INMUEBLES FEDERALES COMPARTIDOS', 'CERTIFICADO DE ASIGNACIÓN DE ESPACIOS EN INMUEBLES FEDERALES COMPARTIDOSCERTIFICADO DE ASIGNACIÓN DE ESPACIOS EN INMUEBLES FEDERALES COMPARTIDOS'), ('CERTIFICADO DE DERECHO DE USO', 'CERTIFICADO DE DERECHO DE USO'), ('COMODATO', 'COMODATO'), ('CONCESIÓN', 'CONCESIÓN'), ('CONVENIO', 'CONVENIO'), ('DECLARATORIA DE SUJECIÓN AL RÉGIMEN DE DOMINIO PÚBLICO', 'DECLARATORIA DE SUJECIÓN AL RÉGIMEN DE DOMINIO PÚBLICO'), ('DECLARATORIAS DE ACUERDO AL ART. 55 LGBN', 'DECLARATORIAS DE ACUERDO AL ART. 55 LGBN'), ('DECRETO DE DESTINO', 'DECRETO DE DESTINO'), ('DECRETO DE EXPROPIACIÓN', 'DECRETO DE EXPROPIACIÓN'), ('DEPÓSITO', 'DEPÓSITO'), ('DESTINO DE HECHO', 'DESTINO DE HECHO'), ('DOCUMENTO DE ASIGNACIÓN DE ESPACIOS', 'DOCUMENTO DE ASIGNACIÓN DE ESPACIOS'), ('NO APLICA', 'NO APLICA'), ('OTROS', 'OTROS')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='expedido_por',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='inscripcion_rppf',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='institucion_propietario',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='propietario_inmueble',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('ENTIDAD PARAESTATAL', 'ENTIDAD PARAESTATAL'), ('GOBIERNO FEDERAL', 'GOBIERNO FEDERAL'), ('ORGANISMO DESCENTRALIZADO NO SECTORIZADOS', 'ORGANISMO DESCENTRALIZADO NO SECTORIZADOS'), ('PODER LEGISLATIVO', 'PODER LEGISLATIVO'), ('PODER JUDICIAL', 'PODER JUDICIAL'), ('INSTITUCIÓN AUTÓNOMA', 'INSTITUCIÓN AUTÓNOMA'), ('ÓRGANO DESCONCENTRADO', 'ÓRGANO DESCONCENTRADO'), ('OTROS', 'OTROS')], default='SIN INFORMACIÓN', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('Escritura Pública', 'Escritura Pública'), ('Contrato', 'Contrato'), ('Acta o Resolución de Adjudicación', 'Acta o Resolución de Adjudicación'), ('Convenio de Cesión', 'Convenio de Cesión'), ('Decreto de Expropiación', 'Decreto de Expropiación'), ('Resolución Judicial', 'Resolución Judicial'), ('Resolución Administrativa', 'Resolución Administrativa'), ('Inmatriculación Administrativa', 'Inmatriculación Administrativa'), ('Declaratoria de Nacionalización', 'Declaratoria de Nacionalización'), ('Acuerdo Ministerial de Aseguramiento de Bienes', 'Acuerdo Ministerial de Aseguramiento de Bienes'), ('Ley o Decreto Constitutivo de una Institución Pública', 'Ley o Decreto Constitutivo de una Institución Pública'), ('Contrato o Aportación a un Fideicomiso', 'Contrato o Aportación a un Fideicomiso'), ('Título de Propiedad', 'Título de Propiedad'), ('Resolución Presidencial Agraria', 'Resolución Presidencial Agraria'), ('Declaratoria de Propiedad Federal', 'Declaratoria de Propiedad Federal'), ('Dación en Pago', 'Dación en Pago'), ('Información Ad Perpetuam', 'Información Ad Perpetuam')], default='SIN INFORMACIÓN', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='institucionesocupantesimp',
            name='superficie_asignada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='institucionesocupantesimp',
            name='superficie_disponible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='institucionesocupantesimp',
            name='uso_institucion_ocupante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeimp',
            name='asunto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeimp',
            name='enviado_por_imp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos_imp', to=settings.AUTH_USER_MODEL, verbose_name='Enviado'),
        ),
        migrations.AlterField(
            model_name='mensajeimp',
            name='enviar_a_imp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados_imp', to=settings.AUTH_USER_MODEL, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='mensajeimp',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocupacionesimp',
            name='estatus_procedimiento',
            field=models.CharField(blank=True, choices=[('sin_informacion', 'SIN INFORMACIÓN'), ('activo', 'ACTIVO'), ('concluido', 'CONCLUIDO')], default='sin_informacion', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ocupacionesimp',
            name='nombre_ocupante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ocupacionesimp',
            name='superficie_invadida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocupacionesimp',
            name='suspension_acto',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ocupacionesimp',
            name='tipo_procedimiento',
            field=models.CharField(blank=True, choices=[('sin_informacion', 'SIN INFORMACIÓN'), ('administrativo', 'ADMINISTRATIVO'), ('averiguacion_previa', 'AVERIGUACIÓN PREVIA'), ('judicial', 'JUDICIAL')], default='sin_informacion', max_length=20, null=True),
        ),
    ]
