# Generated by Django 4.2.3 on 2023-11-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='created',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='updated',
        ),
    ]
