# Generated by Django 5.0.4 on 2024-04-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'permissions': [('add_tasks_inmueble', 'Can add inmueble in tasks app'), ('change_tasks_inmueble', 'Can change inmueble in tasks app'), ('delete_tasks_inmueble', 'Can delete inmueble in tasks app'), ('view_tasks_inmueble', 'Can view inmueble in tasks app')], 'verbose_name': 'Inmueble Importado', 'verbose_name_plural': 'Inmuebles Importados'},
        ),
    ]
