# Generated by Django 5.1.3 on 2025-09-18 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlarchivo',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='observaciones',
            options={},
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='fecha_completado',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='texto',
        ),
        migrations.AddField(
            model_name='observaciones',
            name='fecha_observacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='observaciones_data',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='tasks.inmueble'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='ControlArchivo',
        ),
    ]
