# Generated by Django 5.1.3 on 2025-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='calidad_construccion',
            field=models.CharField(blank=True, choices=[('sin_info', 'Sin Información'), ('buena', 'Buena'), ('de_lujo', 'De Lujo'), ('economica', 'Económica'), ('media', 'Media'), ('muy_buena', 'Muy Buena'), ('otro', 'Otro')], default='sin_info', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='servicios',
            field=models.CharField(blank=True, choices=[('sin_info', 'Sin Información'), ('basicos', 'Básicos'), ('completos', 'Completos'), ('escasos', 'Escasos'), ('sin_servicios', 'Sin Servicios')], default='sin_info', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='zona_ubicacion',
            field=models.CharField(blank=True, choices=[('sin_info', 'Sin Información'), ('rural', 'Rural'), ('semiurbana', 'Semiurbana'), ('urbana', 'Urbana')], default='sin_info', max_length=100, null=True),
        ),
    ]
