# Generated by Django 5.0.4 on 2024-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrollamadas',
            name='NumLlamada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
