# Generated by Django 4.2.3 on 2023-11-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_inmueble_created_remove_inmueble_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
