# Generated by Django 4.2.7 on 2024-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_dictamenestructuralimp_fecha_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictamenestructuralimp',
            name='certificado_de_seguridad',
        ),
        migrations.RemoveField(
            model_name='dictamenestructuralimp',
            name='descripcion_del_sentido_del_Dictamen',
        ),
        migrations.RemoveField(
            model_name='dictamenestructuralimp',
            name='sentido_del_Dictamen',
        ),
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='no_de_identificador_del_expediente_institucion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
