# Generated by Django 4.2.3 on 2023-09-29 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_mensaje_enviado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='enviar_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Inmueble'),
        ),
    ]
