# Generated by Django 4.2.3 on 2023-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_inmueble_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='created',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
