# Generated by Django 5.0.4 on 2024-05-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_datosllamadasinmuebles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datosllamadasinmuebles',
            table=None,
        ),
    ]
