# Generated by Django 4.2.3 on 2023-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_events_delete_task_condia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='UR',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('CGEE', 'CGEE'), ('DGB', 'DGB'), ('DGBTEPD', 'DGBTEPD'), ('DGCFT', 'DGCFT'), ('DGETAyCM', 'DGETAyCM'), ('DGETI', 'DGETI'), ('DGRMyS', 'DGRMyS'), ('RESEMS', 'RESEMS')], default='Activo', max_length=30, null=True),
        ),
    ]
