# Generated by Django 5.0.4 on 2024-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_inmueble_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreInmueble', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del inmueble')),
                ('rfi', models.CharField(blank=True, max_length=15, null=True)),
                ('UR', models.CharField(blank=True, choices=[('CGEE', 'CGEE'), ('DGB', 'DGB'), ('DGBTEPD', 'DGBTEPD'), ('DGCFT', 'DGCFT'), ('DGETAyCM', 'DGETAyCM'), ('DGETI', 'DGETI'), ('DGRMyS', 'DGRMyS'), ('RESEMS', 'RESEMS')], max_length=30, null=True)),
            ],
        ),
    ]
