# Generated by Django 5.1.3 on 2025-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_datosavaluosimp_fecha_valor_de_avaluo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='fecha_creacion_DOC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentopropiedadimp',
            name='inscripcion_registro_local',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='edificacionimp',
            name='tipo_de_inmueble',
            field=models.CharField(blank=True, choices=[('SIN INFORMACION', 'Sin Información'), ('EDIFICACION', 'Edificación'), ('MIXTO', 'Mixto'), ('TERRENO', 'Terreno')], default='SIN INFORMACION', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeimp',
            name='estado',
            field=models.CharField(blank=True, choices=[('Completado', 'Completado'), ('En Revisión', 'En Revision'), ('No Completado', 'No Completado')], default='No Completado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ocupacionesimp',
            name='recuperado',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tramitesdisposicionimp',
            name='estatus',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'Sin Información'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='SIN INFORMACIÓN', max_length=20, null=True),
        ),
    ]
