# Generated by Django 5.1.3 on 2025-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_inmueble_calidad_construccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='calidad_construccion',
            field=models.CharField(blank=True, choices=[('buena', 'Buena'), ('de_lujo', 'De Lujo'), ('economica', 'Económica'), ('media', 'Media'), ('muy_buena', 'Muy Buena'), ('otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='servicios',
            field=models.CharField(blank=True, choices=[('basicos', 'Básicos'), ('completos', 'Completos'), ('escasos', 'Escasos'), ('sin_servicios', 'Sin Servicios')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_asentamiento',
            field=models.CharField(blank=True, choices=[('SIN INFORMACIÓN', 'Sin Información'), ('AEROPUERTO', 'Aeropuerto'), ('AMPLIACIÓN', 'Ampliación'), ('BARRIO', 'Barrio'), ('CANTÓN', 'Cantón'), ('CIUDAD', 'Ciudad'), ('CIUDAD INDUSTRIAL', 'Ciudad Industrial'), ('COLONIA', 'Colonia'), ('CONDOMINIO', 'Condominio'), ('CONJUNTO HABITACIONAL', 'Conjunto Habitacional'), ('CORREDOR INDUSTRIAL', 'Corredor Industrial'), ('COTO', 'Coto'), ('CUARTEL', 'Cuartel'), ('EJIDO', 'Ejido'), ('EXHACIENDA', 'Exhacienda'), ('FRACCIÓN', 'Fracción'), ('FRACCIONAMIENTO', 'Fraccionamiento'), ('GRANJA', 'Granja'), ('HACIENDA', 'Hacienda'), ('INGENIO', 'Ingenio'), ('ISLA', 'Isla'), ('MANZANA', 'Manzana'), ('PARAJE', 'Paraje'), ('PARQUE INDUSTRIAL', 'Parque Industrial'), ('PRIVADA', 'Privada'), ('PROLONGACIÓN', 'Prolongación'), ('PUEBLO', 'Pueblo'), ('PUERTO', 'Puerto'), ('RANCHERIA', 'Ranchería'), ('RANCHO', 'Rancho'), ('REGIÓN', 'Región'), ('RESIDENCIAL', 'Residencial'), ('RINCONADA', 'Rinconada'), ('SECCIÓN', 'Sección'), ('SECTOR', 'Sector'), ('SUPERMANZANA', 'Supermanzana'), ('UNIDAD', 'Unidad'), ('UNIDAD HABITACIONAL', 'Unidad Habitacional'), ('VILLA', 'Villa'), ('ZONA FEDERAL', 'Zona Federal'), ('ZONA INDUSTRIAL', 'Zona Industrial'), ('ZONA MILITAR', 'Zona Militar'), ('ZONA NAVAL', 'Zona Naval')], max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='zona_ubicacion',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('semiurbana', 'Semiurbana'), ('urbana', 'Urbana')], max_length=100, null=True),
        ),
    ]
