# Generated by Django 4.2.3 on 2023-10-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foliosrealesimp',
            name='folios_reales_data',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foliosrealesimp',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios_reales_data', to='tasks.inmueble'),
        ),
    ]
