# Generated by Django 4.2.3 on 2023-09-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_arqueologico_alter_task_artistico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arqueologico',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='artistico',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='historico',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='monumento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('No', 'No')], max_length=2),
        ),
    ]
