# Generated by Django 5.1.3 on 2025-09-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_observacion_comentario_delete_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
