# Generated by Django 5.0.4 on 2024-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_datosllamadasinmuebles_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosllamadasinmuebles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
