# Generated by Django 4.2.7 on 2024-01-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_dictamenestructuralimp_certificado_de_seguridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenestructuralimp',
            name='certificado_de_seguridad',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='dictamenestructuralimp',
            name='descripcion_del_sentido_del_Dictamen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dictamenestructuralimp',
            name='fecha_documento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dictamenestructuralimp',
            name='sentido_del_Dictamen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dictamenestructuralimp',
            name='subir_archivo_dictamen',
            field=models.FileField(blank=True, null=True, upload_to='Dictamen-Estructurales/'),
        ),
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='no_de_identificador_del_expediente_institucion',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
