# Generated by Django 5.0.4 on 2024-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_llamadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadas',
            name='creado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='llamadas',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llamadas',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llamadas',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
