# Generated by Django 5.1.3 on 2025-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_documentopropiedadimp_fecha_creacion_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosllamadasinmuebles',
            name='NombreInmueble',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='seccion_del_inventario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
