# Generated by Django 4.2.3 on 2023-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_foliosrealesimp_folios_reales_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Completado', 'Completado')], default='Activo', max_length=15, null=True),
        ),
    ]
