# Generated by Django 4.2.3 on 2023-11-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_inmueble_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='municipio_no_existente',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
