# Generated by Django 5.1.3 on 2025-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_inmueble_calidad_construccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='uso_dominante_zona',
            field=models.CharField(blank=True, choices=[('COMERCIAL', 'COMERCIAL'), ('DE OFICINAS', 'DE OFICINAS'), ('HABITACIONAL', 'HABITACIONAL'), ('INDUSTRIAL', 'INDUSTRIAL'), ('OTRO', 'OTRO')], max_length=100, null=True),
        ),
    ]
