# Generated by Django 4.2.3 on 2023-10-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_inmueble_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='created',
            new_name='creado',
        ),
    ]
