# Generated by Django 4.2.3 on 2023-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_inmueble_ur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='UR',
            field=models.CharField(blank=True, choices=[('CGEE', 'CGEE'), ('DGB', 'DGB'), ('DGBTEPD', 'DGBTEPD'), ('DGCFT', 'DGCFT'), ('DGETAyCM', 'DGETAyCM'), ('DGETI', 'DGETI'), ('DGRMyS', 'DGRMyS'), ('RESEMS', 'RESEMS')], max_length=30, null=True),
        ),
    ]
