# Generated by Django 4.2.7 on 2024-02-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_dictamenestructuralimp_certificado_de_seguridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='municipio_no_existente',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
