# Generated by Django 5.0.4 on 2024-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_llamadas_creado_llamadas_datecompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadas',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Completado', 'Completado')], default='Activo', max_length=30, null=True),
        ),
    ]
