# Generated by Django 4.2.3 on 2023-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='NombreInmueble',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Completado', 'Completado')], default='Activo', max_length=15, null=True),
        ),
    ]
