# Generated by Django 4.2.3 on 2023-10-05 19:30

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_created_inmueble_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='subir_archivo',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.InmueblesFiles()),
        ),
    ]
