# Generated by Django 5.1.3 on 2025-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_datosllamadasinmuebles_nombreinmueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosllamadasinmuebles',
            name='NombreInmueble',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado_conservacion',
            field=models.CharField(blank=True, choices=[('seleccionar estado', 'Seleccionar el Estado de Conservación'), ('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('ruinoso', 'Ruinoso'), ('muy_bueno', 'Muy Bueno')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre_vialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
