# Generated by Django 5.0.4 on 2024-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_datosllamadasinmuebles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosllamadasinmuebles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
