# Generated by Django 5.1.3 on 2025-08-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_datosllamadasinmuebles_nombreinmueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosllamadasinmuebles',
            name='NombreInmueble',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='Denominaciones_anteriores',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='NombreInmueble',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='usoEspecifico',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
