# Generated by Django 5.0.4 on 2024-04-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_llamadas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadas',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
