# Generated by Django 5.1.3 on 2025-11-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
