# Generated by Django 4.2.3 on 2023-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_inmueble_subir_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='entidad_federativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='municipio_alcaldia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
