# Generated by Django 5.0.4 on 2024-04-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_llamadas_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadas',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10, null=True),
        ),
    ]
