# Generated by Django 5.1.3 on 2025-08-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_datosllamadasinmuebles_nombreinmueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='nombre_asentamiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_exterior_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='poblacion_servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
