# Generated by Django 5.1.3 on 2025-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_inmueble_nombre_asentamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='no_de_identificador_del_expediente_institucion',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='no_de_identificador_del_expediente_institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
