# Generated by Django 4.2.3 on 2023-10-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_mensajeimp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('En Revisión', 'En Revisión'), ('No Completado', 'No Completado')], default='No Completado', max_length=20),
        ),
        migrations.AlterField(
            model_name='foliosrealesimp',
            name='folios_reales_data',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foliosrealesimp',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios_reales', to='tasks.inmueble'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tasks.task', verbose_name='Inmueble'),
        ),
        migrations.AlterField(
            model_name='task',
            name='NombreInmueble',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del inmueble'),
        ),
        migrations.DeleteModel(
            name='MensajeIMP',
        ),
    ]
