# Generated by Django 5.0.4 on 2024-04-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_llamadas_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llamadas',
            old_name='assigned_to',
            new_name='assigned_task',
        ),
    ]
