# Generated by Django 5.1.3 on 2025-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_dictamenestructuralimp_no_de_identificador_del_expediente_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='certificado_de_seguridad',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='descripcion_del_sentido_del_Dictamen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foliosrealesimp',
            name='folios_reales_data',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
