# Generated by Django 4.2.3 on 2023-10-11 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_alter_mensaje_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeIMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('mensaje', models.TextField(null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Completado', 'Completado'), ('En Revisión', 'En Revisión'), ('No Completado', 'No Completado')], default='No Completado', max_length=20)),
                ('enviado_por_imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos_imp', to=settings.AUTH_USER_MODEL, verbose_name='Enviado')),
                ('enviar_a_imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados_imp', to=settings.AUTH_USER_MODEL, verbose_name='Destino')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.inmueble', verbose_name='Inmueble')),
            ],
        ),
    ]
