# Generated by Django 5.1.3 on 2025-09-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_dictamenestructuralimp_certificado_de_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenestructuralimp',
            name='sentido_del_Dictamen',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='expedientes_cedocimp',
            name='expediente_cedoc_data',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='numeroplanoimp',
            name='numero_plano_data',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
