# Generated by Django 5.1.3 on 2025-09-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_dictamenestructuralimp_sentido_del_dictamen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_data', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('fecha_observacion', models.DateField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='tasks.inmueble')),
            ],
        ),
    ]
