# Generated by Django 4.2.3 on 2023-10-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_mensajeimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeimp',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tasks.inmueble', verbose_name='Inmueble'),
        ),
    ]
