# Generated by Django 4.2.3 on 2023-10-11 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_alter_mensajeimp_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_inmueble', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeimp',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('En Revisión', 'En Revision'), ('No Completado', 'No Completado')], default='No Completado', max_length=20),
        ),
    ]
