# Generated by Django 4.2.3 on 2023-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_inmueble_assigned_to_alter_mensajeimp_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeimp',
            name='enlace',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
