# Generated by Django 4.2.3 on 2023-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_mensajeimp_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
