# Generated by Django 4.2.3 on 2023-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_inmueble_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='rfi',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
