# Generated by Django 4.2.3 on 2023-10-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_inmueble_rfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='rfi',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
